-- 明細テーブル
CREATE TABLE detail (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           VARCHAR(200)  NOT NULL,
  status          VARCHAR(12)   NOT NULL, 
  owner_user_id   VARCHAR(64)   NOT NULL,
  version         BIGINT        NOT NULL DEFAULT 0
);

-- よく使う検索に備えたインデックス
CREATE INDEX idx_detail_owner         ON detail (owner_user_id);
CREATE INDEX idx_detail_owner_id      ON detail (owner_user_id, id);
